#!/usr/bin/env expect

set modem [lindex $argv 0];

# keep it open
exec sh -c "sleep 3 < $modem" &

set logfilepath [lindex $argv 1];
log_file -noappend "$logfilepath"
set timeout 1800
set PID [lindex $argv 2]

exec stty -f $modem 9600 raw -clocal -echo -istrip -hup

# connect
send_user "connecting to $modem, exit with ~.\n"
spawn -open [open $modem w+]

# Todo other things here later like login, restart each boot service, shutdown and close expect instead.
expect {
  "login:" {
    send_user "You may now type vm console ghostbsd-openrc-ci and press enter twice to access the VM console."
    sleep 5
    exit 0
  }
}
