# $FreeBSD$

PACKAGE=runtime

CONFS=          bootmisc fsck ipfw ldconfig localmount moused netmount powerd rarpd \
		savecore staticroute swap syscons tmpfiles urandom

NO_OBJ=
CONFDIR=       /etc/conf.d
CONFMODE=      755

.include <bsd.prog.mk>

