#!/bin/sh
#
#

# PROVIDE: os-release
# REQUIRE: mountcritremote FILESYSTEMS
# BEFORE:  LOGIN

. /etc/rc.subr

name="osrelease"
desc="os-release update"
rcvar="osrelease_enable"
start_cmd="osrelease_start"
stop_cmd=":"

load_rc_config $name

: ${osrelease_file:=/var/run/os-release}
: ${osrelease_perms:=444}
: ${osrelease_home_url:="https://www.FreeBSD.org"}
: ${osrelease_documentation_url:="https://docs.FreeBSD.org"}
: ${osrelease_support_url:="https://www.FreeBSD.org/support"}
: ${osrelease_bug_report_url:="https://bugs.FreeBSD.org"}

osrelease_start()
{
	local _version _version_id

	startmsg -n "Updating ${osrelease_file} "	
	_version=$(ghostbsd-version -v)
	_version_id=${_version%%[^0-9.]*}
	t=$(mktemp -t os-release)
	cat > "$t" <<-__EOF__
		NAME="GhostBSD"
		VERSION="$_version"
		VERSION_ID="$_version_id"
		ID="ghostbsd"
		ANSI_COLOR="0;31"
		PRETTY_NAME="GhostBSD $_version"
		CPE_NAME=cpe:/o:ghostbsd:ghostbsd:$_version_id
		HOME_URL=https://GhostBSD.org/
		BUG_REPORT_URL=https://github.com/ghostbsd/issues/issues/new/choose
		CODENAME="Twenty-Six"
__EOF__
	install -C -o root -g wheel -m ${osrelease_perms} "$t" "${osrelease_file}"
	rm -f "$t"
	startmsg 'done.'
}

# doesn't make sense to run in a svcj: config setting
osrelease_svcj="NO"

run_rc_command "$1"
